package com.shidonghui.mymagic.db;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table TREASURE_CHEST_MODEL.
 */
public class TreasureChestModel {

    private String liveId;
    private String startTime;
    private Long watchSeconds;
    private Integer box1Status;
    private Integer box2Status;
    private Integer box3Status;
    private Integer box4Status;
    private Integer box5Status;
    private Integer box6Status;
    private Integer favoriteStatus;
    private Integer shareStatus;

    public TreasureChestModel() {
    }

    public TreasureChestModel(String liveId) {
        this.liveId = liveId;
    }

    public TreasureChestModel(String liveId, String startTime, Long watchSeconds, Integer box1Status, Integer box2Status, Integer box3Status, Integer box4Status, Integer box5Status, Integer box6Status, Integer favoriteStatus, Integer shareStatus) {
        this.liveId = liveId;
        this.startTime = startTime;
        this.watchSeconds = watchSeconds;
        this.box1Status = box1Status;
        this.box2Status = box2Status;
        this.box3Status = box3Status;
        this.box4Status = box4Status;
        this.box5Status = box5Status;
        this.box6Status = box6Status;
        this.favoriteStatus = favoriteStatus;
        this.shareStatus = shareStatus;
    }

    public String getLiveId() {
        return liveId;
    }

    public void setLiveId(String liveId) {
        this.liveId = liveId;
    }

    public String getStartTime() {
        return startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public Long getWatchSeconds() {
        return watchSeconds;
    }

    public void setWatchSeconds(Long watchSeconds) {
        this.watchSeconds = watchSeconds;
    }

    public Integer getBox1Status() {
        return box1Status;
    }

    public void setBox1Status(Integer box1Status) {
        this.box1Status = box1Status;
    }

    public Integer getBox2Status() {
        return box2Status;
    }

    public void setBox2Status(Integer box2Status) {
        this.box2Status = box2Status;
    }

    public Integer getBox3Status() {
        return box3Status;
    }

    public void setBox3Status(Integer box3Status) {
        this.box3Status = box3Status;
    }

    public Integer getBox4Status() {
        return box4Status;
    }

    public void setBox4Status(Integer box4Status) {
        this.box4Status = box4Status;
    }

    public Integer getBox5Status() {
        return box5Status;
    }

    public void setBox5Status(Integer box5Status) {
        this.box5Status = box5Status;
    }

    public Integer getBox6Status() {
        return box6Status;
    }

    public void setBox6Status(Integer box6Status) {
        this.box6Status = box6Status;
    }

    public Integer getFavoriteStatus() {
        return favoriteStatus;
    }

    public void setFavoriteStatus(Integer favoriteStatus) {
        this.favoriteStatus = favoriteStatus;
    }

    public Integer getShareStatus() {
        return shareStatus;
    }

    public void setShareStatus(Integer shareStatus) {
        this.shareStatus = shareStatus;
    }

    @Override
    public String toString() {
        return "TreasureChestModel{" +
                "liveId='" + liveId + '\'' +
                ", startTime='" + startTime + '\'' +
                ", watchSeconds=" + watchSeconds +
                ", box1Status=" + box1Status +
                ", box2Status=" + box2Status +
                ", box3Status=" + box3Status +
                ", box4Status=" + box4Status +
                ", box5Status=" + box5Status +
                ", box6Status=" + box6Status +
                ", favoriteStatus=" + favoriteStatus +
                ", shareStatus=" + shareStatus +
                '}';
    }
}
